### ISSUE TITLE
Port issue 

### ISSUE THREAD

**Issue by Hsidhu** [level7systems/php-sip#1]
Hello,

After update all the settings in example.php. I am facing this  problem

`PHP Warning:  fopen(dev/shm/cache/PhpSIP.lock): failed to open stream: No such file or directory in C:\Users\admin\Documents\hsidhu\local\sites\test\phpSip\PhpSIP.class.php on line 436
PHP Fatal error:  Uncaught PhpSIPException: Can't open lock file. in C:\Users\admin\Documents\hsidhu\local\sites\test\phpSip\PhpSIP.class.php:440
Stack trace:
#0 C:\Users\admin\Documents\hsidhu\local\sites\test\phpSip\PhpSIP.class.php(1612): PhpSIP->releasePort()
#1 C:\Users\admin\Documents\hsidhu\local\sites\test\phpSip\PhpSIP.class.php(310): PhpSIP->closeSocket()
#2 [internal function]: PhpSIP->__destruct()
#3 {main}
  thrown in C:\Users\admin\Documents\hsidhu\local\sites\test\phpSip\PhpSIP.class.php on line 440`

Then I change the permissions on the file and folder but still facing this issue.
But file is been written on each request with the port number started from min_port to max_port like this ->

5068,5069,5070,5071,5072,5073..... so on

**Comment by l7s** [comment]
Hi, the reason you are getting this error is `/dev/shm/cache/PhpSIP.lock` is not a valid file path on Windows platform. You would need to edit line below:

https://github.com/level7systems/php-sip/blob/master/PhpSIP.class.php#L57

and change it to some path on your Windows PC where lock file should be created.

Regards,
Chris
