### ISSUE TITLE
407 Proxy Authentication Required

### ISSUE THREAD

**Issue by wjgilmore** [level7systems/php-sip#3]
Hi,

I'm sorry to bother you but I'm at wits' end attempting to get past this `407 Proxy Authentication Required` issue. I'm providing my SIP username and password using setUsername() and setPassword(), respectively. I've confirmed the authentication works by way of making a successful call using Zoiper. Yet no matter what I do with the `php-sip` package I receive the 407 Proxy Authentication response.

--> INVITE sip:6149998888@gw1.sip.us SIP/2.0 <-- SIP/2.0 100 Trying 

<-- SIP/2.0 407 Proxy Authentication Required 

--> ACK sip:6149998888@gw1.sip.us SIP/2.0 --> INVITE sip:6142099975@gw1.sip.us SIP/2.0 

<-- SIP/2.0 100 Trying New dialog: 92381.2484f1a5f06b7307c34ab1dd8d74150a.33cc.29daf5ef3b7663e00f2db8077dee2963@173.236.165.43 

<-- SIP/2.0 407 Proxy Authentication Required --> ACK sip:6149998888@gw1.sip.us SIP/2.0

Any ideas? My code is effectively identical to that used in the README (SIP numbers/passwords etc removed):

```
<?php

require_once('PhpSIP.class.php');

    try {

      // if you get "Failed to obtain IP address to bind. Please set bind address manualy."
      // error, use the line below instead
      $api = new PhpSIP();

      $api->setDebug(true);

      $api->setUsername('123456789');
      $api->setPassword('password');

      $api->addHeader('Subject: click2call');
      $api->setMethod('INVITE');
      $api->setFrom('sip:123456789@gw1.sip.us');
      $api->setUri('sip:6149998888@gw1.sip.us');

      $res = $api->send();

      if ($res == 200) {

        $api->setMethod('REFER');
        $api->addHeader('Refer-to: sip:6149998888@gw1.sip.us');
        $api->addHeader('Referred-By: sip:123456789@gw1.sip.us');
        $api->send();

        $api->setMethod('BYE');
        $api->send();

        $api->listen('NOTIFY');
        $api->reply(481,'Call Leg/Transaction Does Not Exist');
      }

      if ($res == 'No final response in 5 seconds.') {
        $api->setMethod('CANCEL');
        $res = $api->send();
      }

      echo "RESULT: " . $res;

    } catch (Exception $e) {

      echo "Oops... Caught exception:";

      echo $e;
    }
```

**Comment by gaethofs** [comment]
How did you resolve this?

**Comment by wjgilmore** [comment]
Hi @gaethofs I have no idea why I closed the issue without any followup response, and apologize. I spent *days* working on this before finally giving in and calling SIP providers until I could get an expert on the phone. IIRC he told me what I was trying to do wouldn't work, at which point I called it quits. This was a side project, and never went anywhere.

**Comment by ethaniel** [comment]
Fixed the send() function in this commit: https://github.com/level7systems/php-sip/pull/13
I also added a helpful function getCode(), so the call progress can be tracked.

I updated the code to suit my needs (I want to check if a call can be established), but you can get the idea:

```php
$api = new PhpSIP();

$api->setDebug(true);

$api->setUsername('admin');
$api->setPassword('password');

$api->addHeader('Subject: call');
$api->setMethod('INVITE');

// username + server hostname
$api->setFrom('sip:admin@myhost.com');

// who we are calling
$api->setUri('sip:12223334455@myhost.com');

/*
1. this sends the initial INVITE
2. then handles the response of 100 Trying
3. then waits for the 401 Unauthorized
4. and then reissues the INVITE.
5. returns 100 Trying
*/
$res = $api->send(); 

if ($res == 100) {
	// received "SIP/2.0 100 Trying". We should already be authorized at this point.

	$res = $api->getCode();
	if ($res == 180) {
		// received "SIP/2.0 180 Ringing"

		// $api->setMethod('BYE'); // can hangup here, not wait for session progress
		// $res = $api->send();


		$res = $api->getCode();
		if ($res == 183) {
			// received "SIP/2.0 183 Session Progress"

			$api->setMethod('BYE'); // hang up immediately
			$res = $api->send();

		}
	}
}

if ($res == 'No final response in 5 seconds.') {
	$api->setMethod('CANCEL');
	$res = $api->send();
}
```

**Comment by ethaniel** [comment]
@level7systems can you please reopen this issue and apply the commit?
