### ISSUE TITLE
Receive INVITE

### ISSUE THREAD

**Issue by danielfigueroaj** [level7systems/php-sip#6]
After logging in successfully, how can I receive an INVITE? (I don't need to establish the call, just want to read the SIP incoming invite from any other softphone outside)

Thanks, great job!

**Comment by l7s** [comment]
Hi, for this you would need to use `setServerMode(true);` [here](https://github.com/level7systems/php-sip/blob/11122c272657942a344874180eded5566c0e9ec4/PhpSIP.class.php#L899)
