### ISSUE TITLE
How listen to invite?

### ISSUE THREAD

**Issue by serge-stotskiy** [level7systems/php-sip#8]
Help please. Need to accept invite and send back 302 redirect https://blog.opensips.org/2018/07/05/handling-sip-redirect-requests-in-realtime/ . Thanks.

**Comment by l7s** [comment]
Hi, to do that, you would need to call `setServerMode(true)` after creating an instance of `PhpSIP`
Regards,
Chris

**Comment by serge-stotskiy** [comment]
Hello, @l7s . Please tell me how to listen to the event correctly?
```
$api = new PhpSIP();
$api->setServerMode(true)
$api->setUsername($user);
$api->setPassword($password);
$api->listen('INVITE');
$api->reply(302,'Redirect call');
```
What number should I accept the invitation to? I am trying to send an invitation to $user. Tried also to accept the invitation from sip: 92071022@192.168.1.39 . Outgoing calls, messages are working, but I cannot receive incoming calls, messages.
